# Generated by Django 2.0.1 on 2018-10-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20181022_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
